config/routes.rb
require 'api_constraints'

Resapi::Application.routes.draw do

	root :to => 'home#index'

	namespace :api, :defaults => {:format => :json} do
	 	scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
	    get '(/:ingredient(/:action(/:id)))', controller: 'base'
	  end
	end

	resources :ingredients
	resources :data_sources

	get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  # mount Resque::Server, :at => "/resque"
end

app/models/data_source.rb
class DataSource
  include Mongoid::Document
  belongs_to :data_source_type
  before_save :set_ip_address

  belongs_to :user
  has_one :ingredient

  validates_presence_of :name, :data_file

  field :name
  field :coordinates, :type => Array
  field :ip_address
  field :location
  field :image
  field :status
  field :preview, :type => Hash
  field :header_row

  TYPES = [:file, :api]

  include Geocoder::Model::Mongoid
  geocoded_by :address

  mount_uploader :data_file, FileUploader

  def address
  	self.location || self.ip_address	
  end


  private

  def set_ip_address
    self.ip_address = self.user.last_ip || ""
  end
end

app/models/data_source_type.rb
class DataSourceType
  include Mongoid::Document


  field :name
  field :format


end

app/controllers/data_sources_controller.rb
class DataSourcesController < ApplicationController
  before_action :set_data_source, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /data_sources
  # GET /data_sources.json
  def index
    @data_sources = DataSource.where(:user => current_user)
  end

  # GET /data_sources/1
  # GET /data_sources/1.json
  def show
    # binding.pry
  end

  # GET /data_sources/new
  def new
    @data_source = DataSource.new
  end

  # GET /data_sources/1/edit
  def edit
  end

  # POST /data_sources
  # POST /data_sources.json
  def create
    @data_source = DataSource.new(data_source_params)
    @data_source.user = current_user
    @data_source.status = "uploaded"

    respond_to do |format|
      if @data_source.save
        Resque.enqueue(DownloadDataSourceJob, @data_source.id)
        format.html { redirect_to @data_source, notice: 'Data source was successfully created.' }
        format.json { render action: 'show', status: :created, location: @data_source }
      else
        format.html { render action: 'new' }
        format.json { render json: @data_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_sources/1
  # PATCH/PUT /data_sources/1.json
  def update
    respond_to do |format|
      if @data_source.update(data_source_params)
        Resque.enqueue(DownloadDataSourceJob, @data_source.id) if data_source_params.include? :data_file
        format.html { redirect_to @data_source, notice: 'Data source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @data_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_sources/1
  # DELETE /data_sources/1.json
  def destroy
    @data_source.destroy
    respond_to do |format|
      format.html { redirect_to data_sources_url }
      format.json { head :no_content }
    end
  end

  def serve_data_file
    content = @data_source.data_file
    if stale?(etag: content, last_modified: @data_file.updated_at.utc, public: true)
      send_data content, type: @data_file.data_file.file.content_type, disposition: "inline"
      expires_in 0, public: true
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_source
      @data_source = DataSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_source_params
      params[:data_source].permit(:name, :image, :data_file)
    end
end

app/helpers/data_sources_helper.rb
module DataSourcesHelper
end

app/views/data_sources/_form.html.haml
= simple_form_for(@data_source) do |f|
  = f.error_notification

  - if @data_source.errors.any?
    %div.alert.alert-error
      - @data_source.errors.messages.each do |message|
        %span= message[0].to_s.titleize
        %span= message[1][0].to_s
        %br

  .form-inputs
    = f.label :name
    = f.text_field :name

    = f.label :data_file
    = f.file_field :data_file

  .form-actionss
    = f.button :submit

app/views/data_sources/edit.html.haml
%h1 Editing data_source

= render 'form'

= link_to 'Show', @data_source
\|
= link_to 'Back', data_sources_path

app/views/data_sources/index.html.haml
%h1 Listing data_sources

%table
  %tr
    %th
      Name
    %th
    %th
      Actions
    %th

  - @data_sources.each do |data_source|
    %tr
      %td= data_source.name
      %td= link_to 'Show', data_source
      %td= link_to 'Edit', edit_data_source_path(data_source)
      %td= link_to 'Destroy', data_source, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Data source', new_data_source_path

app/views/data_sources/new.html.haml
%h1 New data_source

= render 'form'

= link_to 'Back', data_sources_path

app/views/data_sources/show.html.haml
%ul
	%li= @data_source.name
	- if @data_source.data_file
		%li= link_to 'Download', @data_source.data_file.to_s

- if @data_source.errors
	- @data_source.errors.each do |error|
		%p.error= error.message
		
= link_to 'Edit', edit_data_source_path(@data_source)
\|
= link_to 'Back', data_sources_path

%hr
= debug @data_source