config/routes.rb
require 'api_constraints'

Resapi::Application.routes.draw do

	root :to => 'home#index'

	namespace :api, :defaults => {:format => :json} do
	 	scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
	    get '(/:ingredient(/:action(/:id)))', controller: 'base'
	  end
	end

	resources :ingredients
	resources :data_sources

	get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  # mount Resque::Server, :at => "/resque"
end

app/models/ingredient.rb
class Ingredient
  include Mongoid::Document
  belongs_to :user
  belongs_to :data_source
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

	def index
		@ingredients = Ingredient.all
		@recent_ingredients = Ingredient.all.limit(10)
	end


	def new
		@ingredient = Ingredient.new
		@data_source = DataSource.new
		@data_source_types = DataSourceType.all
	end

	private
		def ingredient_params
      params.require(:ingredient).permit(
		    	:name,
		    	:data_source_type => [:id]
        )
    end

    def set_ingredient
    	@ingredient = Ingredient.find(params[:id])
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_external_source.html.slim
/ <%= form_for @article, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
/   <%= f.text_field :title %>
/   <%= f.text_area :body, size: "60x12" %>
/   <%= f.submit "Create" %>
/ <% end %>
/ f.file_field :profile_photo


/# = form_for @ingredient, url:{ action: "create" }, html: {class: "nifty_form"} do |f|
	/ = f.text_field :name

/ = form_for [@data_source, @data_source_types], html: { class: "nifty_form" } do |f|
/ 	= f.select :data_source_type

/ 	= f.submit "Create"


h1
	| Upload your dataset..


/ = form_for @ingredient do |f|

app/views/ingredients/_recent.html.slim
h2
	| Recently created APIs
- @recent_ingredients.each do |ingredient|
	= ingredient.try(:name)


- if @recent_ingredients.empty?
	p
		| There are currently <u>no</u> recently created APIs.

app/views/ingredients/_upload.html.slim
h1
	| Upload your dataset..

= form_for(@ingredient) do |f|
	/ # = f.text_field :name

	= f.submit "Submit"

	=debug @ingredient

app/views/ingredients/index.html.slim
.row
	.span8
		= link_to "New", new_ingredient_path

	.span4
		= render :partial => 'recent'

app/views/ingredients/new.html.slim
= render :partial => 'upload'