config/routes.rb
require 'api_constraints'

Resapi::Application.routes.draw do

	root :to => 'home#index'

	namespace :api, :defaults => {:format => :json} do
	 	scope :module => :v1, :constraints => ApiConstraints.new(:version => 1, :default => true) do
	    get '(/:ingredient(/:action(/:id)))', controller: 'base'
	  end
	end

	resources :ingredients
	resources :data_sources

	get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  # mount Resque::Server, :at => "/resque"
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? "success" : "error"}") 
      a.close data-dismiss="alert"  ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
= link_to "resapi", root_path, :class => 'brand'
ul.nav
	li class=('active' if is_active?(ingredients_path))
		= link_to "Ingredients", ingredients_path
	li class=('active' if is_active?(data_sources_path))
		= link_to "Data Sources", data_sources_path

span.tagline
	| Cookin' up APIs
	
ul.nav.pull-right
	li
		- if user_signed_in?
			= link_to "Sign out", signout_path
		- else
			= link_to 'Login', signin_path, { 'data-no-turbolink' => true }

app/views/layouts/_search.html.slim
form action="/search" method="GET" class="form-search"
	input type="text" class="input-medium search-query input-xlarge" placeholder="Enter terms to search or a zip code" name="name" value="#{params[:name]}"
	button type="submit" class="btn btn-primary"
		| Search

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport" 
      title= content_for?(:title) ? yield(:title) : "resapi.org"
      meta content=(content_for?(:description) ? yield(:description) : "resapi.org") name="description" 
        = stylesheet_link_tag "application", :media => "all"
        = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Scada:400,700|Cardo:400,700"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  body class=("#{controller_name} #{action_name}") data-party_id=("#{@party_id}")
    .navbar.navbar-fixed-top
      nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main role="main" 
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          footer
      /! ! end of .container
    /! ! end of #main


javascript:
  var party_id = $('body').data('party_id');
  $(function() {
    // $.deck('.slide');

    var dispatcher = new WebSocketRails('localhost:5000/websocket');

    // subscribe to the channel
    var channel = dispatcher.subscribe('party_'+presentation_id);

    console.log(channel)
    // bind to a channel event
    channel.bind('party_'+presentation_id, function(data) {
      console.log('channel event received: ' + data);
      //$('.debug').append(data)
      //$('#goto-slide').val(data.slide)
    });
  })